config/routes.rb
ChallegeMe::Application.routes.draw do
  root to: redirect('/signin')
  resources :users
  resources :challenges, only: [:create, :show]
  resources :sessions, only: [:new, :create, :destroy]

  match 'auth/:provider/callback', to: "sessions#create", via: [:get, :post]
  match 'auth/failure', to: 'sessions#failed_authentication', via: [:get, :post]
  match 'signin', to: 'sessions#new', as: 'signin', via: [:get]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get]

  

end

app/models/challenge.rb
class Challenge < ActiveRecord::Base
	before_save { self.description = description.titleize }
	has_and_belongs_to_many :users
	default_scope -> { order('created_at DESC') }

	def self.all_types
		[	
			"pushups",
			"running",
			"pie-eating",
			"donkey racing",
			"yak shaving",
			"karate",
			"karaoke",
			"knitting",
			"horse back riding",
			"a chili cookoff",
			"jello wrestling",
			"carpet cleaning",
			"chess",
			"checkers",
			"scrabble",
			"jenga",
			"lawnmowing",
			"blood donation",
			"looking like steve jobs",
			"coffee brewing",
			"body hiding",
			"water filtration",
			"pasta making",
			"pea shooting",
			"moustache growing",
			"pokemon battling",
			"air guitar",
			"rock paper scissors",
			"curling",
			"jamaican bobsledding",
			"cheese rolling",
			"extreme ironing",
			"javelin",
			"shoelace tying",
			"sheep counting",
			"spin the bottle",
			"hot dog eating",
			"pumpkin catapaulting",
			"ostrich racing",
			"yodeling",
			"tug o war",
			"table tennis",
			"don't spill the beans",
			"cat herding",
			"being the ugliest",
			"arm wrestling",
			"fly fishing",
			"spelling",
			"chest hair removal",
			"fire breathing",
			"lego tower building",
			"falcon training",
			"having the most hobbit-like feet",
			"billboard painting",
			"bird watching",
			"bluetooth device ownership",
			"janitorial services",
			"self-tattooing",
			"being the worst",
			"having the most elaborate neck tattoo",
			"cockfighting",
			"wurst-making",
			"fish tossing",
			"having the longest nose hairs",
			"being a beautiful young lady and a old ugly lady all at once",
			"toenail growing",
			"mohawk ownership",
			"navel-gazing",
			"designer sneaker ownership",
			"having the biggest 80s rock hair",
			"being the most offensive",
			"having the most heinous B.O.",
			"being a diversity hire",
			"unibrow cultivation",
			"flamingo figurine collecting",
			"bee wrangling",
			"yelling the loudest at computers",
			"identifying the most with Dilbert",
			"sushi rolling",
			"dodgeball",
			"sportsball",
			"handegg",
			"googling",
			"myspace profile updating",
			"emoji memorizaition",
			"slapfighting",
			"having t-rex arms",
			"vinyl collecting",
			"bicycle repair",
			"breaking the 5 second rule",
			"pinata bashing",
			"being the sassiest cat",
			"having the biggest glasses",
			"being the most twee",
			"having the sickest fixie",
			"having heard about it first",
			"having been into it before it was cool",
			"putting a bird on it",
			"pickling the most things",
			"being the most pedantic",
			"posting the most instagrams",
			"step 1: stealing underwear, step 2: ????, step 3: profit!!",
		]	
	end
end

app/models/champion.rb
class Champion < ActiveRecord::Base
	before_save { self.name = name.titleize }

	validates :name, presence: true
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_and_belongs_to_many :challenges
	has_one :champion

	validates :name, presence: true, length: { maximum: 15 }

	extend FriendlyId
	friendly_id :name

	def self.search query
		if query.present?
			where("name @@ :q", q: query)
		else
			all
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  	def current_user
    	@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def current_user_google
		@current_user_google ||= User.find_by google_id: (session[:user_id_google]) if session[:user_id_google]
	end
		
	helper_method :current_user
	helper_method :current_user_google
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
	respond_to :html, :json

	def create
		challenged_user = User.find(params[:challenged_user])
		challenge = complete_challenge challenged_user, current_user

		redirect_to challenge_path(challenge.id)
	end

	def show
		@challenge = Challenge.find(params[:id])
		@winner = User.find(@challenge.winner_id)
		@loser = User.find(@challenge.loser_id)
		respond_with([@challenge, @winner, @loser])
	end

	private

	def complete_challenge challenged, challenger
		winner, loser = [challenged, challenger].shuffle
		challenge = Challenge.create(description: Challenge.all_types.sample,
																 winner_id: winner.id,
																 loser_id: loser.id,
																)

		winner.challenges << challenge
		loser.challenges << challenge
		update_wins_losses winner, loser

		challenge
	end

	def update_wins_losses winner, loser
		winner.update_attributes(wins: winner.wins + 1)
		loser.update_attributes(losses: loser.losses + 1)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		if session[:user_id].nil?

			user = User.find_by_name auth["info"]["nickname"]

			if user
				user.update(uid: auth["uid"])
			else
				builder = UserBuilder.new
				user = builder.build auth
			end

			session[:user_id] = user.id
			flash[:success] = "Welcome to Challenge Champion!"
		end
		
		redirect_to users_path
	end

	def destroy
		session[:user_id] = nil
		flash.keep[:success] = "Signed out!"
		redirect_to signin_path
	end

	def failed_authentication
		flash.keep[:error] = "Something went wrong!"
		redirect_to signin_path
	end

	protected

	def auth
		env['omniauth.auth']
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	respond_to :html, :json

	def index
		if params[:search]
			@users = User.search(params[:search]).paginate(page: params[:page])
		else
			@users = User.paginate(page: params[:page])
		end
		respond_with(@users)
	end

	def new
		@user = User.new
		respond_with(@user)
	end

	def show
		@user = User.friendly.find(params[:id])
		@challenges = @user.challenges.paginate(page: params[:page])
		respond_with([@user, @challenges])
	end

	def create
		@user = User.new(user_profile_params)
		if @user.save
			redirect_to @user
		else
			render 'new'
		end
	end

	private

	def sign_in_user
		redirect_to signin_url, notice: "Please sign in." unless current_user
	end

  	def user_profile_params
    	params.require(:user).permit(:name)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def current_user?(user)
		if user.id == current_user.id
			true
		else
			false
		end
	end

	def champion(user)
		emojify ":#{user.champion.name.downcase.tr(" ", "_")}:"
	end
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/helpers/emoji_helper.rb
module EmojiHelper
	def emojify(content)
		h(content).to_str.gsub(/:([\w+-]+):/) do |match|
			if emoji = Emoji.find_by_alias($1)
				%(<img alt="#$1" src="#{image_path("emoji/#{emoji.image_filename}")}" style="vertical-align:middle" width="20" height="20" />)
			else
				match
			end
		end.html_safe if content.present?
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def signed_in?
		current_user
	end
end

app/helpers/users_helper.rb
module UsersHelper
	def winner_name(users, winner_id)
		if current_user.id == winner_id
			"YOU"
		else
			winner = User.all.find(winner_id)
			if winner.blank?
				"UNKNOWN"
			else
				winner.name
			end
		end
	end

	def loser_name(users, loser_id)
		if current_user.id == loser_id
			"YOU"
		else
			loser = User.all.find(loser_id)
			if loser.blank?
				"UNKNOWN"
			else
				loser.name
			end
		end
	end
end

app/views/challenges/index.html.erb
<h1><%= @user.name %>, represented by the brave and loyal <%= champion(name) %></h1><br>
<% unless current_user?(@user) %>
	<%= button_to "Challenge", challenges_path(:challenged_user => @user.id), method: :post %>
<% end %>


<h3>Challenge History</h3>
<p>
  Wins: <%= @user.wins %>
  Losses: <%= @user.losses %>
</p>

<h3>Recent Contests</h3>
<ol>
	<% @challenges.each do |challenge| %>
		<li>
			<%= winner_name(challenge.users, challenge.winner_id) champion(@user) %>
			defeated
			<%= loser_name(challenge.users, challenge.loser_id) champion(@user) %>
			at
			<%= challenge.description.downcase %>
		</li>
	<% end %>
</ol>

app/views/challenges/show.html.erb
<h1>Challenge Complete!</h1>

<div class="challenge">
	<h2><%= @challenge.description %></h2>
</div>

<div class="challenge-result" id="winner">
	<h3>Winner<br>
		<%= @winner.name %>'s <%= champion(@winner) %></h3>
</div>

<div class="challenge-result" id="loser">
	<h3>Loser<br>
	<%= @loser.name %>'s <%= champion(@loser) %></h3>
</div>

app/views/layouts/_challenge.html.erb
<li id="<%= challenge.id %>">
	<span class="user">
		<%= winner_name(challenge.users, challenge.winner_id) %>
		defeated
		<%= loser_name(challenge.users, challenge.loser_id) %>
		at
		<%= challenge.description.downcase %>
		<br>
	</span>
	<span class="timestamp">
		<%= time_ago_in_words(challenge.created_at) %> ago
	</span>
</li>

app/views/layouts/_contests.html.erb
<% if @challenges.any? %>
	<ol class="challenges">
		<%= render partial: 'layouts/challenge', collection: @challenges %>
	</ol>
	<%= will_paginate @challenges %>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Challenge Champion", '#', id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Challenge Someone", 	users_path %></li>
					<% if signed_in? %>
						<li><%= link_to "My Champion",	user_path(current_user.name) %></li>
						<li><%= link_to "Sign Out",	signout_path %></li>
					<% else %>
						
						<li><%= link_to "Sign In", "/auth/twitter" %></li>
					<% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Challenge Champion</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |key, value| %>
			<div class="alert alert-<%= key %>"><%= value %></div>
		<% end %>

		<% if signed_in? %>
			<div class="pull-right">
				Signed into Twitter as <%= current_user.name %>!
			</div>
			<%= yield %>
		<% end %>

	</div>

</body>

</html>

app/views/users/_user.html.erb
<div class="span3">
	<div class="hero-widget well well-sm">
		<div class="icon">
			<i class="glyphicon glyphicon-user"></i>
		</div>
		<div class="text">
			<h3><%= link_to "#{user.name}", user_path(user.id) %></h3>
			<label>Represented by the brave and loyal</label>
			<var><%= champion(user) %></var>
			<var>Wins: <%= user.wins %></var>
			<var>Losses: <%= user.losses %></var>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<div class="row">
	<h1>Challengers</h1>
</div>

<div class='row'>
	<%= form_tag('/users', method: :get, class: 'form-search form-horizontal pull-left', id: 'custom-search-form') do %>
		<div class='input-append'>
			<%= text_field_tag(:search, nil, placeholder: 'Enter Twitter username..', class: 'search-query') %>
			<%= button_tag(type:'submit', class: 'btn') do %>
				<i class='icon-search'></i>
			<% end %>
		</div>
	<% end %>
</div>

<div class='row'>
	<%= will_paginate %>

	<% if @users.any? %>
		<% @users.in_groups_of(3) do |group| %>
			<div class="row">
				<% group.compact.each do |user| %>
					<%= render user %>
				<% end %>
			</div>
		<% end %>
	<% else %>
		No results found.
	<% end %>

	<%= will_paginate %>
</div>

app/views/users/show.html.erb
<% if signed_in? %>
	<div class="row">
		<aside class="span5">
			<section>
				<h1><%= @user.name %></h1>
				<h4>represented by the brave and loyal</h4>
				<h4><%= champion(@user) %></h4>
			</section>
			<section>
				<h2>Challenge History</h2>
				<h4>Wins: <%= @user.wins %></h4>
				<h4>Losses: <%= @user.losses %></h4>
			</section>
			<section>
				<div class="challenge">
					<% unless current_user?(@user) %>
						<%= button_to raw("Challenge #{@user.name} to a contest!"), challenges_path(:challenged_user => @user.id), 
													class: "btn btn-successi btn-large", method: :post %>
					<% end %>
				</div>
			</section>
		</aside>
	<div class="span6">
		<h2>Recent Contests</h2>
		<%= render 'layouts/contests' %>
	</div>
<% else %>
	<h1>Welcome to ChallengeChampion!</h1>
<% end %>